function Hd = bandpass_filter
%BANDPASS_FILTER Returns a discrete-time filter object.

%
% M-File generated by MATLAB(R) 7.5 and the Signal Processing Toolbox 6.8.
%
% Generated on: 17-Mar-2008 01:05:03
%

% Butterworth Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in kHz.
Fs = 48;  % Sampling Frequency

N   = 100;  % Order
Fc1 = 5;    % First Cutoff Frequency
Fc2 = 11;   % Second Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandpass('N,Fc1,Fc2', N, Fc1, Fc2, Fs);
Hd = design(h, 'butter');

% [EOF]
