function Hd = lowpass_filter
%LOWPASS_FILTER Returns a discrete-time filter object.

%
% M-File generated by MATLAB(R) 7.5 and the Signal Processing Toolbox 6.8.
%
% Generated on: 17-Mar-2008 01:08:43
%

% FIR Window Nyquist filter designed using the FIRNYQUIST function.

% All frequency values are in kHz.
Fs = 48;  % Sampling Frequency

N    = 100;  % Order
Beta = 0.5;  % Window Parameter
L    = 5;    % Band

% Create the window vector for the design algorithm.
win = kaiser(N+1, Beta);

% Calculate the coefficients with the FIRNYQUIST function.
b  = firnyquist(N, L, win);
Hd = dfilt.dffir(b);

% [EOF]
